### ISSUE TITLE
Is this plugin related to flutter_adyen on PubDev?

### ISSUE THREAD

**Issue by davidkohcw** [skiprco/flutter-adyen#1]
Hi!

Just curious, is this the same plugin as https://pub.dev/packages/flutter_adyen? It seems that the repository link on that page is broken and does not link here.

That aside, is this plugin working/actively maintained? Because the last version on that plugin page was in Oct 2019.

Thanks!

**Comment by benoitskipr** [comment]
so sry I missed the msg, it is a fork of that flutter_adyen lib (that is not actively maintained) that fits our needs at Skipr, fixes some bugs, and adds some settings/features.
we made it public mostly for information purposes.
